### PR TITLE
Refactor person fields

### PR DESCRIPTION
**Pull request by kevinchangjk**
This is a PR purely for minor changes that I had been planning on doing for a while.

- Made *NULL* values of optional `Person` fields accessible through static methods only
- Change of two word commands to include hyphens
    - `batchadd` to `batch-add`
    - `addleave` to `add-leave`
    - `deleteleave` to `delete-leave`
    - `viewdepartment` to `view-department`
- Cleanup of coding standards and code quality
- Fix mouse event bug leading to index out of bounds exception in log (terminal)
- Fix exception thrown sometimes when data file is tampered/corrupted

As mentioned, these are a bunch of random changes altogether, many of these not really discussed with you all yet (*whoops sorry*). Please take a look through and give feedback and suggestions.

### CODE REVIEW

**Comment by chao890** [comment]
LGTM

**Review by chao890 — APPROVED** [review]
Good

**Comment by kevinchangjk** [comment]
Will fix #180 .

**Review by prit3010 — APPROVED** [review]
lgtm

**Pull request merged**
